version: '3'
services:
  surreal:
    image: surrealdb/surrealdb:latest
    entrypoint: /surreal start --log warn --auth file:/data/surrealdb
    volumes:
      - data:/data

  server:
    image: mivinci/halo-server:latest
    ports:
      - 23003:3000
    depends_on:
      - surrealdb
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET}

      - SURREAL_URL=${SURREAL_URL}
      - SURREAL_NS=${SURREAL_NS}
      - SURREAL_DB=${SURREAL_DB}
      - SURREAL_USER=${SURREAL_USER}
      - SURREAL_PASS=${SURREAL_PASS}

      - OPENAI_URL=${OPENAI_URL}
      - OPENAI_KEY=${OPENAI_KEY}

      - COS_SECRET_ID=${COS_SECRET_ID}
      - COS_SECRET_KEY=${COS_SECRET_KEY}
      - COS_REGION=${COS_REGION}
      - COS_BUCKET=${COS_BUCKET}

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: /data
      o: bind
